export type Calculator = {
  slug: string;
  title: string;
  emoji: string;
  color: string;
};

export const ALL_CALCULATORS: Calculator[] = [
  { slug: "/salaire-brut-net", title: "Salaire Brut / Net", emoji: "💰", color: "from-blue-500 to-indigo-500" },
  { slug: "/calcul-tva", title: "Calcul TVA", emoji: "🧾", color: "from-emerald-500 to-teal-500" },
  { slug: "/simulateur-pret-immobilier", title: "Pret Immobilier", emoji: "🏠", color: "from-violet-500 to-purple-500" },
  { slug: "/calcul-pourcentage", title: "Calcul Pourcentage", emoji: "📊", color: "from-orange-500 to-amber-500" },
  { slug: "/calcul-imc", title: "Calcul IMC", emoji: "⚖️", color: "from-rose-500 to-pink-500" },
  { slug: "/frais-de-notaire", title: "Frais de Notaire", emoji: "📋", color: "from-cyan-500 to-blue-500" },
  { slug: "/calcul-consommation-electrique", title: "Consommation Electrique", emoji: "⚡", color: "from-yellow-500 to-orange-500" },
  { slug: "/calcul-age", title: "Calcul Age", emoji: "🎂", color: "from-pink-500 to-rose-500" },
  { slug: "/indemnite-licenciement", title: "Indemnite Licenciement", emoji: "📄", color: "from-indigo-500 to-purple-500" },
  { slug: "/convertisseur-devises", title: "Convertisseur Devises", emoji: "💱", color: "from-sky-500 to-blue-600" },
  { slug: "/calcul-surface-peinture", title: "Surface Peinture", emoji: "🎨", color: "from-fuchsia-500 to-pink-500" },
  { slug: "/simulateur-epargne", title: "Simulateur Epargne", emoji: "🏦", color: "from-emerald-500 to-green-600" },
  { slug: "/calcul-heures-travail", title: "Heures de Travail", emoji: "⏰", color: "from-amber-500 to-orange-500" },
  { slug: "/calcul-indemnites-kilometriques", title: "Indemnites Kilometriques", emoji: "🚗", color: "from-teal-500 to-cyan-600" },
  { slug: "/simulateur-impot-revenu", title: "Simulateur Impot", emoji: "🏛️", color: "from-red-500 to-rose-600" },
  { slug: "/calcul-date-accouchement", title: "Date d'Accouchement", emoji: "🤰", color: "from-purple-500 to-pink-500" },
  { slug: "/simulateur-dca", title: "Simulateur DCA", emoji: "📈", color: "from-green-500 to-emerald-600" },
  { slug: "/calculateur-inflation", title: "Calculateur Inflation", emoji: "📉", color: "from-red-500 to-orange-500" },
  { slug: "/simulateur-apl", title: "Simulateur APL", emoji: "🏘️", color: "from-teal-500 to-cyan-600" },
  { slug: "/calcul-calories", title: "Calcul Calories", emoji: "🔥", color: "from-green-500 to-emerald-600" },
  { slug: "/calcul-masse-grasse", title: "Masse Grasse", emoji: "🏋️", color: "from-violet-500 to-purple-500" },
  { slug: "/calcul-macros", title: "Calcul Macros", emoji: "🥗", color: "from-violet-500 to-purple-600" },
  { slug: "/simulateur-chomage", title: "Simulateur Chomage", emoji: "📋", color: "from-sky-500 to-blue-600" },
  { slug: "/simulateur-micro-entreprise", title: "Micro-Entreprise", emoji: "🏢", color: "from-violet-500 to-purple-600" },
  { slug: "/calcul-ovulation", title: "Calcul Ovulation", emoji: "🌸", color: "from-pink-500 to-rose-500" },
  { slug: "/calcul-taux-endettement", title: "Taux d'Endettement", emoji: "🏦", color: "from-blue-500 to-indigo-500" },
  { slug: "/simulateur-mobilisation", title: "Simulateur Mobilisation", emoji: "🪖", color: "from-slate-700 to-slate-900" },
  { slug: "/simulateur-bombe-nucleaire", title: "Bombe Nucleaire", emoji: "☢️", color: "from-red-600 to-orange-600" },
  { slug: "/simulateur-bunker", title: "Budget Bunker", emoji: "🛡️", color: "from-amber-600 to-orange-700" },
  { slug: "/simulateur-pension-alimentaire", title: "Pension Alimentaire", emoji: "👨‍👧", color: "from-indigo-500 to-purple-600" },
  { slug: "/calcul-cout-garde-enfant", title: "Cout Garde Enfant", emoji: "👶", color: "from-pink-500 to-rose-600" },
  { slug: "/simulateur-credit-conso", title: "Credit Conso", emoji: "💳", color: "from-blue-500 to-indigo-600" },
  { slug: "/simulateur-bonus-ecologique", title: "Bonus Ecologique Auto", emoji: "🚗", color: "from-green-500 to-emerald-600" },
  { slug: "/calcul-prime-activite", title: "Prime d'Activite", emoji: "💰", color: "from-emerald-500 to-teal-600" },
  { slug: "/simulateur-retraite", title: "Simulateur Retraite", emoji: "🏖️", color: "from-teal-500 to-emerald-600" },
  { slug: "/simulateur-salaire-alternant", title: "Salaire Alternant", emoji: "🎓", color: "from-indigo-500 to-purple-500" },
  { slug: "/calculateur-budget-survie", title: "Budget Survie", emoji: "🧮", color: "from-red-500 to-orange-500" },
  { slug: "/calculateur-autonomie", title: "Autonomie Financiere", emoji: "⏳", color: "from-amber-500 to-red-500" },
  { slug: "/simulateur-blackout", title: "Simulateur Blackout", emoji: "🔦", color: "from-slate-700 to-slate-900" },
  { slug: "/calcul-capacite-emprunt", title: "Capacite d'Emprunt", emoji: "🏠", color: "from-blue-600 to-indigo-600" },
  { slug: "/prix-macon", title: "Prix Macon", emoji: "🧱", color: "from-amber-500 to-orange-600" },
  { slug: "/prix-peintre", title: "Prix Peintre", emoji: "🎨", color: "from-violet-500 to-purple-600" },
  { slug: "/prix-electricien", title: "Prix Electricien", emoji: "⚡", color: "from-blue-500 to-indigo-600" },
  { slug: "/prix-plombier", title: "Prix Plombier", emoji: "🔧", color: "from-cyan-500 to-teal-600" },
  { slug: "/prix-couvreur", title: "Prix Couvreur", emoji: "🪜", color: "from-red-700 to-amber-600" },
  { slug: "/prix-chauffagiste", title: "Prix Chauffagiste", emoji: "🔥", color: "from-orange-600 to-red-500" },
  { slug: "/prix-panneaux-solaires", title: "Prix Panneaux Solaires", emoji: "☀️", color: "from-amber-400 to-yellow-500" },
  { slug: "/conversion-temperature", title: "Conversion Temperature", emoji: "🌡️", color: "from-blue-500 to-indigo-600" },
  { slug: "/conversion-poids", title: "Conversion Poids", emoji: "⚖️", color: "from-emerald-500 to-teal-600" },
  { slug: "/conversion-longueur", title: "Conversion Longueur", emoji: "📏", color: "from-orange-500 to-amber-600" },
  { slug: "/calcul-moyenne", title: "Calcul Moyenne", emoji: "🎓", color: "from-violet-500 to-purple-600" },
  { slug: "/produit-en-croix", title: "Produit en Croix", emoji: "✖️", color: "from-sky-500 to-blue-600" },
  { slug: "/calcul-conges-payes", title: "Calcul Conges Payes", emoji: "🏖️", color: "from-teal-500 to-cyan-600" },
  { slug: "/calcul-plus-value-immobiliere", title: "Plus-Value Immobiliere", emoji: "🏡", color: "from-green-500 to-emerald-600" },
  { slug: "/calcul-rentabilite-locative", title: "Rentabilite Locative", emoji: "🏢", color: "from-amber-500 to-orange-600" },
  { slug: "/calcul-revenus-fonciers", title: "Revenus Fonciers", emoji: "🏘️", color: "from-indigo-500 to-violet-600" },
  { slug: "/calcul-consommation-essence", title: "Consommation Essence", emoji: "⛽", color: "from-red-500 to-rose-600" },
  { slug: "/calcul-jours-ouvres", title: "Jours Ouvres", emoji: "📅", color: "from-indigo-500 to-purple-600" },
  { slug: "/calcul-interet-compose", title: "Interet Compose", emoji: "📈", color: "from-cyan-500 to-blue-600" },
  { slug: "/calcul-malus-ecologique", title: "Malus Ecologique", emoji: "🚗", color: "from-rose-500 to-red-600" },
  { slug: "/calcul-pgcd-ppcm", title: "PGCD / PPCM", emoji: "🔢", color: "from-purple-500 to-violet-600" },
  { slug: "/calcul-duree-entre-dates", title: "Duree Entre Dates", emoji: "📆", color: "from-fuchsia-500 to-pink-600" },
  { slug: "/verificateur-devis", title: "Verificateur Devis", emoji: "📋", color: "from-blue-600 to-indigo-700" },
  { slug: "/modele-devis-btp", title: "Modele Devis BTP", emoji: "🧾", color: "from-blue-500 to-indigo-600" },
  { slug: "/calcul-ascendant-astrologique", title: "Ascendant Astro", emoji: "♈", color: "from-purple-500 to-indigo-600" },
  { slug: "/calcul-gratification-stage", title: "Gratification Stage", emoji: "🎓", color: "from-indigo-500 to-blue-600" },
  { slug: "/calcul-droits-succession", title: "Droits Succession", emoji: "⚖️", color: "from-slate-700 to-slate-900" },
  { slug: "/simulateur-cout-voiture", title: "Cout Total Voiture", emoji: "🚗", color: "from-blue-600 to-indigo-600" },
  { slug: "/calcul-cout-kilometrique", title: "Cout Kilometrique", emoji: "🚙", color: "from-sky-500 to-blue-600" },
  { slug: "/calcul-pension-reversion", title: "Pension Reversion", emoji: "💜", color: "from-violet-500 to-purple-600" },
  { slug: "/calcul-surface-cercle", title: "Surface Cercle", emoji: "⭕", color: "from-blue-500 to-cyan-600" },
  { slug: "/calcul-volume-cylindre", title: "Volume Cylindre", emoji: "🛢️", color: "from-teal-500 to-emerald-600" },
  { slug: "/calcul-racine-carree", title: "Racine Carree", emoji: "√", color: "from-amber-500 to-orange-600" },
  { slug: "/calcul-poids-ideal", title: "Poids Ideal", emoji: "⚖️", color: "from-violet-500 to-purple-600" },
  { slug: "/calcul-metabolisme-base", title: "Metabolisme de Base", emoji: "🔥", color: "from-orange-500 to-red-500" },
  { slug: "/calcul-proteines", title: "Apport Proteines", emoji: "🥩", color: "from-red-500 to-rose-600" },
  { slug: "/calcul-besoin-sommeil", title: "Besoin Sommeil", emoji: "🌙", color: "from-indigo-500 to-purple-600" },
  { slug: "/calcul-consommation-eau", title: "Consommation Eau", emoji: "💧", color: "from-blue-500 to-cyan-500" },
  { slug: "/calcul-age-metabolique", title: "Age Metabolique", emoji: "🧬", color: "from-violet-500 to-purple-600" },
  { slug: "/calcul-risque-cardiovasculaire", title: "Risque Cardiovasculaire", emoji: "❤️", color: "from-red-600 to-rose-600" },
  { slug: "/calcul-indice-glycemique", title: "Indice Glycemique", emoji: "🌿", color: "from-green-500 to-emerald-600" },
  { slug: "/calculateur-dpe", title: "Simulateur DPE", emoji: "🏠", color: "from-emerald-500 to-green-600" },
  { slug: "/simulateur-facture-gaz", title: "Facture Gaz", emoji: "🔥", color: "from-orange-500 to-red-500" },
  { slug: "/simulateur-credit-auto", title: "Credit Auto", emoji: "🚙", color: "from-blue-500 to-indigo-600" },
  { slug: "/calcul-score-stress", title: "Score Stress", emoji: "🧠", color: "from-violet-500 to-purple-600" },
  { slug: "/simulateur-electrique-vs-thermique", title: "Electrique vs Thermique", emoji: "⚡", color: "from-green-500 to-emerald-600" },
  { slug: "/calcul-vignette-critair", title: "Vignette Crit'Air", emoji: "🚗", color: "from-amber-500 to-orange-600" },
  { slug: "/calcul-remboursement-mutuelle", title: "Remboursement Mutuelle", emoji: "🏥", color: "from-cyan-500 to-blue-600" },
  { slug: "/calcul-allocation-familiale", title: "Allocation Familiale", emoji: "👨‍👩‍👧‍👦", color: "from-green-500 to-emerald-600" },
  { slug: "/calcul-taxe-fonciere", title: "Taxe Fonciere", emoji: "🏠", color: "from-amber-500 to-yellow-600" },
  { slug: "/simulateur-assurance-emprunteur", title: "Assurance Emprunteur", emoji: "🛡", color: "from-indigo-500 to-purple-600" },
  { slug: "/simulateur-rendement-scpi", title: "Rendement SCPI", emoji: "🏢", color: "from-teal-500 to-cyan-600" },
  { slug: "/simulateur-rente-viagere", title: "Rente Viagere", emoji: "🏦", color: "from-amber-500 to-orange-600" },
  { slug: "/calcul-ifi", title: "Calcul IFI", emoji: "🏛", color: "from-rose-500 to-pink-600" },
  { slug: "/simulateur-impot-societe", title: "Simulateur IS", emoji: "🏦", color: "from-blue-500 to-indigo-600" },
  { slug: "/simulateur-amende-exces-vitesse", title: "Amende Vitesse", emoji: "🚨", color: "from-red-500 to-orange-600" },
  { slug: "/simulateur-loa-lld", title: "LOA vs LLD", emoji: "🚘", color: "from-sky-500 to-blue-600" },
  { slug: "/calcul-indice-inflammation", title: "Indice Inflammation", emoji: "🥗", color: "from-emerald-500 to-red-500" },
  { slug: "/calcul-prestation-compensatoire", title: "Prestation Compensatoire", emoji: "⚖️", color: "from-violet-500 to-purple-600" },
  { slug: "/calcul-prise-poids-grossesse", title: "Prise Poids Grossesse", emoji: "🤰", color: "from-pink-500 to-rose-600" },
  { slug: "/calcul-amortissement-lmnp", title: "Amortissement LMNP", emoji: "🏠", color: "from-teal-500 to-emerald-600" },
  { slug: "/simulateur-dividendes", title: "Simulateur Dividendes", emoji: "💎", color: "from-violet-500 to-purple-600" },
  { slug: "/audit-frais-bancaires", title: "Audit Frais Bancaires", emoji: "🔍", color: "from-red-500 to-orange-600" },
  { slug: "/convertisseur-sensibilite-fps", title: "Sensibilite FPS", emoji: "🎯", color: "from-teal-600 to-cyan-700" },
  { slug: "/convertisseur-allure-course", title: "Allure Course", emoji: "🏃", color: "from-emerald-600 to-teal-700" },
  { slug: "/calcul-ffmi", title: "Calcul FFMI", emoji: "💪", color: "from-violet-600 to-purple-700" },
  { slug: "/convertisseur-monnaie-jeu", title: "Monnaie Jeu Video", emoji: "🎮", color: "from-fuchsia-600 to-pink-700" },
  { slug: "/calcul-vma", title: "Calcul VMA", emoji: "🏃", color: "from-emerald-600 to-teal-700" },
  { slug: "/calcul-1rm", title: "Calcul 1RM", emoji: "🏋️", color: "from-violet-600 to-purple-700" },
  { slug: "/calcul-calories-sport", title: "Calories par Sport", emoji: "🔥", color: "from-orange-500 to-red-500" },
  { slug: "/calcul-fov-jeu", title: "Convertisseur FOV", emoji: "🎯", color: "from-teal-600 to-cyan-700" },
  { slug: "/calcul-temps-telechargement", title: "Temps Telechargement", emoji: "⬇️", color: "from-cyan-500 to-blue-600" },
  { slug: "/calcul-zakat", title: "Zakat al-Mal", emoji: "🕋", color: "from-emerald-600 to-green-700" },
  { slug: "/calcul-zakat-al-fitr", title: "Zakat al-Fitr", emoji: "📿", color: "from-emerald-600 to-green-700" },
  { slug: "/convertisseur-calendrier-hijri", title: "Calendrier Hijri", emoji: "🌙", color: "from-teal-600 to-emerald-700" },
  { slug: "/calcul-date-ramadan", title: "Date Ramadan", emoji: "☪️", color: "from-emerald-600 to-teal-700" },
  { slug: "/calcul-date-paques", title: "Date Paques", emoji: "🕊️", color: "from-amber-500 to-orange-600" },
  { slug: "/signe-astrologique-chinois", title: "Signe Chinois", emoji: "🐉", color: "from-rose-600 to-red-700" },
  { slug: "/calcul-fetes-catholiques", title: "Fetes Catholiques", emoji: "⛪", color: "from-amber-500 to-orange-600" },
  { slug: "/calcul-kaffara-ramadan", title: "Kaffara Ramadan", emoji: "🕌", color: "from-emerald-600 to-green-700" },
  { slug: "/convertisseur-calendrier-hebraique", title: "Calendrier Hebraique", emoji: "✡️", color: "from-blue-600 to-indigo-700" },
  { slug: "/calcul-date-bar-mitzvah", title: "Bar / Bat Mitzvah", emoji: "📜", color: "from-blue-600 to-indigo-700" },
  { slug: "/calcul-ftp-cyclisme", title: "FTP Cyclisme", emoji: "🚴", color: "from-orange-500 to-red-600" },
  { slug: "/calcul-handicap-golf-whs", title: "Handicap Golf WHS", emoji: "⛳", color: "from-green-600 to-emerald-700" },
  { slug: "/calcul-allure-natation", title: "Allure Natation", emoji: "🏊", color: "from-cyan-500 to-blue-600" },
  { slug: "/calcul-classement-tennis-fft", title: "Classement Tennis FFT", emoji: "🎾", color: "from-yellow-500 to-orange-600" },
  { slug: "/calcul-rapport-taille-tour-de-taille", title: "WtHR Sante", emoji: "❤️", color: "from-rose-500 to-pink-600" },
  { slug: "/calcul-age-chien-humain", title: "Age Chien Humain", emoji: "🐕", color: "from-amber-500 to-orange-600" },
  { slug: "/calcul-age-chat-humain", title: "Age Chat Humain", emoji: "🐱", color: "from-orange-400 to-amber-600" },
  { slug: "/calcul-ration-chien", title: "Ration Chien", emoji: "🍖", color: "from-amber-500 to-orange-600" },
  { slug: "/calcul-calories-chien-chat", title: "Calories Chien Chat", emoji: "🐾", color: "from-orange-500 to-red-500" },
  { slug: "/calcul-dose-medicament-animaux", title: "Dose Medicament Animaux", emoji: "💊", color: "from-blue-500 to-cyan-600" },
  { slug: "/calcul-signe-zodiaque", title: "Signe Zodiaque", emoji: "✨", color: "from-violet-600 to-purple-700" },
  { slug: "/calcul-chemin-de-vie", title: "Chemin de Vie", emoji: "🔮", color: "from-purple-600 to-indigo-700" },
  { slug: "/compatibilite-signes-astrologiques", title: "Compatibilite Astro", emoji: "💕", color: "from-pink-500 to-rose-600" },
  { slug: "/calcul-signe-lunaire", title: "Signe Lunaire", emoji: "🌙", color: "from-slate-700 to-indigo-800" },
  { slug: "/numerologie-nom-prenom", title: "Numerologie Nom", emoji: "✨", color: "from-purple-600 to-fuchsia-700" },
  { slug: "/calcul-mention-bac", title: "Mention au Bac", emoji: "🎓", color: "from-blue-500 to-indigo-600" },
  { slug: "/calcul-age-corrige-prema", title: "Age Corrige Prema", emoji: "👶", color: "from-pink-500 to-rose-600" },
  { slug: "/calcul-percentile-bebe", title: "Percentile Bebe", emoji: "📊", color: "from-purple-500 to-pink-600" },
  { slug: "/calcul-cycles-sommeil", title: "Cycles Sommeil", emoji: "🛌", color: "from-indigo-500 to-purple-600" },
  { slug: "/calcul-dette-sommeil", title: "Dette Sommeil", emoji: "😴", color: "from-indigo-600 to-purple-700" },
  { slug: "/test-depression-phq9", title: "Test Depression PHQ-9", emoji: "🧠", color: "from-rose-600 to-pink-700" },
  { slug: "/test-anxiete-gad7", title: "Test Anxiete GAD-7", emoji: "😰", color: "from-amber-500 to-orange-600" },
  { slug: "/test-burnout-mbi", title: "Test Burnout MBI", emoji: "🔥", color: "from-red-500 to-orange-600" },
  { slug: "/calcul-cote-argus-voiture", title: "Cote Argus Voiture", emoji: "🚗", color: "from-blue-500 to-indigo-600" },
  { slug: "/calcul-cout-trajet-voiture", title: "Cout Trajet Voiture", emoji: "🛣️", color: "from-sky-500 to-blue-600" },
  { slug: "/calcul-octroi-de-mer", title: "Octroi de Mer", emoji: "🚢", color: "from-cyan-500 to-blue-600" },
  { slug: "/calcul-exoneration-lodeom", title: "Exoneration LODEOM", emoji: "🏝️", color: "from-teal-500 to-emerald-600" },
  { slug: "/calcul-reduction-impot-dom", title: "Reduction Impot DOM", emoji: "🌴", color: "from-emerald-500 to-green-600" },
  { slug: "/simulateur-girardin-industriel", title: "Girardin Industriel", emoji: "🏭", color: "from-slate-500 to-gray-600" },
  { slug: "/simulateur-denormandie", title: "Simulateur Denormandie", emoji: "🏘️", color: "from-amber-500 to-orange-600" },
  { slug: "/prix-travaux-maison", title: "Prix Travaux Maison", emoji: "🏗️", color: "from-orange-500 to-amber-600" },
  { slug: "/calculateur-gain-pari", title: "Gain de Pari", emoji: "🎰", color: "from-green-500 to-emerald-600" },
  { slug: "/calculateur-pari-combine", title: "Pari Combine", emoji: "🎲", color: "from-violet-500 to-purple-600" },
  { slug: "/convertisseur-cote-probabilite", title: "Cote / Probabilite", emoji: "📈", color: "from-indigo-500 to-blue-600" },
];
