const ALL_CALCULATORS = [
  { slug: "/salaire-brut-net", title: "Salaire Brut / Net", emoji: "💰", color: "from-blue-500 to-indigo-500" },
  { slug: "/calcul-tva", title: "Calcul TVA", emoji: "🧾", color: "from-emerald-500 to-teal-500" },
  { slug: "/simulateur-pret-immobilier", title: "Pret Immobilier", emoji: "🏠", color: "from-violet-500 to-purple-500" },
  { slug: "/calcul-pourcentage", title: "Calcul Pourcentage", emoji: "📊", color: "from-orange-500 to-amber-500" },
  { slug: "/calcul-imc", title: "Calcul IMC", emoji: "⚖️", color: "from-rose-500 to-pink-500" },
  { slug: "/frais-de-notaire", title: "Frais de Notaire", emoji: "📋", color: "from-cyan-500 to-blue-500" },
  { slug: "/calcul-consommation-electrique", title: "Consommation Electrique", emoji: "⚡", color: "from-yellow-500 to-orange-500" },
  { slug: "/calcul-age", title: "Calcul Age", emoji: "🎂", color: "from-pink-500 to-rose-500" },
  { slug: "/indemnite-licenciement", title: "Indemnite Licenciement", emoji: "📄", color: "from-indigo-500 to-purple-500" },
  { slug: "/convertisseur-devises", title: "Convertisseur Devises", emoji: "💱", color: "from-sky-500 to-blue-600" },
  { slug: "/calcul-surface-peinture", title: "Surface Peinture", emoji: "🎨", color: "from-fuchsia-500 to-pink-500" },
  { slug: "/simulateur-epargne", title: "Simulateur Epargne", emoji: "🏦", color: "from-emerald-500 to-green-600" },
  { slug: "/calcul-heures-travail", title: "Heures de Travail", emoji: "⏰", color: "from-amber-500 to-orange-500" },
  { slug: "/calcul-indemnites-kilometriques", title: "Indemnites Kilometriques", emoji: "🚗", color: "from-teal-500 to-cyan-600" },
  { slug: "/simulateur-impot-revenu", title: "Simulateur Impot", emoji: "🏛️", color: "from-red-500 to-rose-600" },
  { slug: "/calcul-date-accouchement", title: "Date d'Accouchement", emoji: "🤰", color: "from-purple-500 to-pink-500" },
  { slug: "/simulateur-dca", title: "Simulateur DCA", emoji: "📈", color: "from-green-500 to-emerald-600" },
  { slug: "/calculateur-inflation", title: "Calculateur Inflation", emoji: "📉", color: "from-red-500 to-orange-500" },
  { slug: "/simulateur-apl", title: "Simulateur APL", emoji: "🏘️", color: "from-teal-500 to-cyan-600" },
  { slug: "/calcul-calories", title: "Calcul Calories", emoji: "🔥", color: "from-green-500 to-emerald-600" },
  { slug: "/calcul-masse-grasse", title: "Masse Grasse", emoji: "🏋️", color: "from-violet-500 to-purple-500" },
  { slug: "/calcul-macros", title: "Calcul Macros", emoji: "🥗", color: "from-violet-500 to-purple-600" },
  { slug: "/simulateur-chomage", title: "Simulateur Chomage", emoji: "📋", color: "from-sky-500 to-blue-600" },
  { slug: "/simulateur-micro-entreprise", title: "Micro-Entreprise", emoji: "🏢", color: "from-violet-500 to-purple-600" },
  { slug: "/calcul-ovulation", title: "Calcul Ovulation", emoji: "🌸", color: "from-pink-500 to-rose-500" },
  { slug: "/calcul-taux-endettement", title: "Taux d'Endettement", emoji: "🏦", color: "from-blue-500 to-indigo-500" },
  { slug: "/simulateur-mobilisation", title: "Simulateur Mobilisation", emoji: "🪖", color: "from-slate-700 to-slate-900" },
  { slug: "/simulateur-bombe-nucleaire", title: "Bombe Nucleaire", emoji: "☢️", color: "from-red-600 to-orange-600" },
  { slug: "/simulateur-bunker", title: "Budget Bunker", emoji: "🛡️", color: "from-amber-600 to-orange-700" },
  { slug: "/simulateur-pension-alimentaire", title: "Pension Alimentaire", emoji: "👨‍👧", color: "from-indigo-500 to-purple-600" },
  { slug: "/calcul-cout-garde-enfant", title: "Cout Garde Enfant", emoji: "👶", color: "from-pink-500 to-rose-600" },
  { slug: "/simulateur-credit-conso", title: "Credit Conso", emoji: "💳", color: "from-blue-500 to-indigo-600" },
  { slug: "/simulateur-bonus-ecologique", title: "Bonus Ecologique Auto", emoji: "🚗", color: "from-green-500 to-emerald-600" },
  { slug: "/calcul-prime-activite", title: "Prime d'Activite", emoji: "💰", color: "from-emerald-500 to-teal-600" },
  { slug: "/simulateur-retraite", title: "Simulateur Retraite", emoji: "🏖️", color: "from-teal-500 to-emerald-600" },
  { slug: "/simulateur-salaire-alternant", title: "Salaire Alternant", emoji: "🎓", color: "from-indigo-500 to-purple-500" },
  { slug: "/calculateur-budget-survie", title: "Budget Survie", emoji: "🧮", color: "from-red-500 to-orange-500" },
  { slug: "/calculateur-autonomie", title: "Autonomie Financiere", emoji: "⏳", color: "from-amber-500 to-red-500" },
  { slug: "/simulateur-blackout", title: "Simulateur Blackout", emoji: "🔦", color: "from-slate-700 to-slate-900" },
  { slug: "/calcul-capacite-emprunt", title: "Capacite d'Emprunt", emoji: "🏠", color: "from-blue-600 to-indigo-600" },
  { slug: "/prix-macon", title: "Prix Macon", emoji: "🧱", color: "from-amber-500 to-orange-600" },
  { slug: "/prix-peintre", title: "Prix Peintre", emoji: "🎨", color: "from-violet-500 to-purple-600" },
  { slug: "/prix-electricien", title: "Prix Electricien", emoji: "⚡", color: "from-blue-500 to-indigo-600" },
  { slug: "/prix-plombier", title: "Prix Plombier", emoji: "🔧", color: "from-cyan-500 to-teal-600" },
  { slug: "/prix-couvreur", title: "Prix Couvreur", emoji: "🪜", color: "from-red-700 to-amber-600" },
  { slug: "/prix-chauffagiste", title: "Prix Chauffagiste", emoji: "🔥", color: "from-orange-600 to-red-500" },
  { slug: "/conversion-temperature", title: "Conversion Temperature", emoji: "🌡️", color: "from-blue-500 to-indigo-600" },
  { slug: "/conversion-poids", title: "Conversion Poids", emoji: "⚖️", color: "from-emerald-500 to-teal-600" },
  { slug: "/conversion-longueur", title: "Conversion Longueur", emoji: "📏", color: "from-orange-500 to-amber-600" },
  { slug: "/calcul-moyenne", title: "Calcul Moyenne", emoji: "🎓", color: "from-violet-500 to-purple-600" },
  { slug: "/produit-en-croix", title: "Produit en Croix", emoji: "✖️", color: "from-sky-500 to-blue-600" },
  { slug: "/calcul-conges-payes", title: "Calcul Conges Payes", emoji: "🏖️", color: "from-teal-500 to-cyan-600" },
  { slug: "/calcul-plus-value-immobiliere", title: "Plus-Value Immobiliere", emoji: "🏡", color: "from-green-500 to-emerald-600" },
  { slug: "/calcul-rentabilite-locative", title: "Rentabilite Locative", emoji: "🏢", color: "from-amber-500 to-orange-600" },
  { slug: "/calcul-revenus-fonciers", title: "Revenus Fonciers", emoji: "🏘️", color: "from-indigo-500 to-violet-600" },
  { slug: "/calcul-consommation-essence", title: "Consommation Essence", emoji: "⛽", color: "from-red-500 to-rose-600" },
  { slug: "/calcul-jours-ouvres", title: "Jours Ouvres", emoji: "📅", color: "from-indigo-500 to-purple-600" },
  { slug: "/calcul-interet-compose", title: "Interet Compose", emoji: "📈", color: "from-cyan-500 to-blue-600" },
  { slug: "/calcul-malus-ecologique", title: "Malus Ecologique", emoji: "🚗", color: "from-rose-500 to-red-600" },
  { slug: "/calcul-pgcd-ppcm", title: "PGCD / PPCM", emoji: "🔢", color: "from-purple-500 to-violet-600" },
  { slug: "/calcul-duree-entre-dates", title: "Duree Entre Dates", emoji: "📆", color: "from-fuchsia-500 to-pink-600" },
  { slug: "/verificateur-devis", title: "Verificateur Devis", emoji: "📋", color: "from-blue-600 to-indigo-700" },
  { slug: "/calcul-ascendant-astrologique", title: "Ascendant Astro", emoji: "♈", color: "from-purple-500 to-indigo-600" },
  { slug: "/calcul-gratification-stage", title: "Gratification Stage", emoji: "🎓", color: "from-indigo-500 to-blue-600" },
  { slug: "/calcul-droits-succession", title: "Droits Succession", emoji: "⚖️", color: "from-slate-700 to-slate-900" },
  { slug: "/simulateur-cout-voiture", title: "Cout Total Voiture", emoji: "🚗", color: "from-blue-600 to-indigo-600" },
  { slug: "/calcul-cout-kilometrique", title: "Cout Kilometrique", emoji: "🚙", color: "from-sky-500 to-blue-600" },
  { slug: "/calcul-pension-reversion", title: "Pension Reversion", emoji: "💜", color: "from-violet-500 to-purple-600" },
  { slug: "/calcul-surface-cercle", title: "Surface Cercle", emoji: "⭕", color: "from-blue-500 to-cyan-600" },
  { slug: "/calcul-volume-cylindre", title: "Volume Cylindre", emoji: "🛢️", color: "from-teal-500 to-emerald-600" },
  { slug: "/calcul-racine-carree", title: "Racine Carree", emoji: "√", color: "from-amber-500 to-orange-600" },
  { slug: "/calcul-poids-ideal", title: "Poids Ideal", emoji: "⚖️", color: "from-violet-500 to-purple-600" },
  { slug: "/calcul-metabolisme-base", title: "Metabolisme de Base", emoji: "🔥", color: "from-orange-500 to-red-500" },
  { slug: "/calcul-proteines", title: "Apport Proteines", emoji: "🥩", color: "from-red-500 to-rose-600" },
  { slug: "/calcul-besoin-sommeil", title: "Besoin Sommeil", emoji: "🌙", color: "from-indigo-500 to-purple-600" },
  { slug: "/calcul-consommation-eau", title: "Consommation Eau", emoji: "💧", color: "from-blue-500 to-cyan-500" },
  { slug: "/calcul-age-metabolique", title: "Age Metabolique", emoji: "🧬", color: "from-violet-500 to-purple-600" },
  { slug: "/calcul-risque-cardiovasculaire", title: "Risque Cardiovasculaire", emoji: "❤️", color: "from-red-600 to-rose-600" },
  { slug: "/calcul-indice-glycemique", title: "Indice Glycemique", emoji: "🌿", color: "from-green-500 to-emerald-600" },
  { slug: "/calculateur-dpe", title: "Simulateur DPE", emoji: "🏠", color: "from-emerald-500 to-green-600" },
  { slug: "/simulateur-facture-gaz", title: "Facture Gaz", emoji: "🔥", color: "from-orange-500 to-red-500" },
  { slug: "/simulateur-credit-auto", title: "Credit Auto", emoji: "🚙", color: "from-blue-500 to-indigo-600" },
  { slug: "/calcul-score-stress", title: "Score Stress", emoji: "🧠", color: "from-violet-500 to-purple-600" },
  { slug: "/simulateur-electrique-vs-thermique", title: "Electrique vs Thermique", emoji: "⚡", color: "from-green-500 to-emerald-600" },
  { slug: "/calcul-vignette-critair", title: "Vignette Crit'Air", emoji: "🚗", color: "from-amber-500 to-orange-600" },
  { slug: "/calcul-remboursement-mutuelle", title: "Remboursement Mutuelle", emoji: "🏥", color: "from-cyan-500 to-blue-600" },
  { slug: "/calcul-allocation-familiale", title: "Allocation Familiale", emoji: "👨‍👩‍👧‍👦", color: "from-green-500 to-emerald-600" },
  { slug: "/calcul-taxe-fonciere", title: "Taxe Fonciere", emoji: "🏠", color: "from-amber-500 to-yellow-600" },
  { slug: "/simulateur-assurance-emprunteur", title: "Assurance Emprunteur", emoji: "🛡", color: "from-indigo-500 to-purple-600" },
  { slug: "/simulateur-rendement-scpi", title: "Rendement SCPI", emoji: "🏢", color: "from-teal-500 to-cyan-600" },
  { slug: "/simulateur-rente-viagere", title: "Rente Viagere", emoji: "🏦", color: "from-amber-500 to-orange-600" },
  { slug: "/calcul-ifi", title: "Calcul IFI", emoji: "🏛", color: "from-rose-500 to-pink-600" },
  { slug: "/simulateur-impot-societe", title: "Simulateur IS", emoji: "🏦", color: "from-blue-500 to-indigo-600" },
  { slug: "/simulateur-amende-exces-vitesse", title: "Amende Vitesse", emoji: "🚨", color: "from-red-500 to-orange-600" },
  { slug: "/simulateur-loa-lld", title: "LOA vs LLD", emoji: "🚘", color: "from-sky-500 to-blue-600" },
  { slug: "/calcul-indice-inflammation", title: "Indice Inflammation", emoji: "🥗", color: "from-emerald-500 to-red-500" },
  { slug: "/calcul-prestation-compensatoire", title: "Prestation Compensatoire", emoji: "⚖️", color: "from-violet-500 to-purple-600" },
  { slug: "/calcul-prise-poids-grossesse", title: "Prise Poids Grossesse", emoji: "🤰", color: "from-pink-500 to-rose-600" },
  { slug: "/calcul-amortissement-lmnp", title: "Amortissement LMNP", emoji: "🏠", color: "from-teal-500 to-emerald-600" },
  { slug: "/simulateur-dividendes", title: "Simulateur Dividendes", emoji: "💎", color: "from-violet-500 to-purple-600" },
];

const RELATED_MAP: Record<string, string[]> = {
  "/salaire-brut-net": ["/simulateur-impot-revenu", "/indemnite-licenciement", "/calcul-heures-travail", "/calcul-indemnites-kilometriques"],
  "/calcul-tva": ["/calcul-pourcentage", "/frais-de-notaire", "/convertisseur-devises", "/salaire-brut-net"],
  "/simulateur-pret-immobilier": ["/calcul-taux-endettement", "/frais-de-notaire", "/simulateur-epargne", "/simulateur-impot-revenu"],
  "/calcul-pourcentage": ["/calcul-tva", "/salaire-brut-net", "/simulateur-epargne", "/convertisseur-devises"],
  "/calcul-imc": ["/calcul-poids-ideal", "/calcul-calories", "/calcul-age", "/calcul-date-accouchement"],
  "/frais-de-notaire": ["/simulateur-pret-immobilier", "/simulateur-impot-revenu", "/calcul-tva", "/simulateur-epargne"],
  "/calcul-consommation-electrique": ["/calcul-surface-peinture", "/calcul-pourcentage", "/simulateur-epargne", "/calcul-tva"],
  "/calcul-age": ["/calcul-date-accouchement", "/calcul-imc", "/calcul-heures-travail", "/simulateur-epargne"],
  "/indemnite-licenciement": ["/salaire-brut-net", "/calcul-heures-travail", "/simulateur-impot-revenu", "/calcul-indemnites-kilometriques"],
  "/convertisseur-devises": ["/calcul-tva", "/calcul-pourcentage", "/salaire-brut-net", "/simulateur-epargne"],
  "/calcul-surface-peinture": ["/calcul-consommation-electrique", "/simulateur-pret-immobilier", "/frais-de-notaire", "/calcul-pourcentage"],
  "/simulateur-epargne": ["/simulateur-impot-revenu", "/simulateur-pret-immobilier", "/salaire-brut-net", "/convertisseur-devises"],
  "/calcul-heures-travail": ["/salaire-brut-net", "/indemnite-licenciement", "/calcul-indemnites-kilometriques", "/simulateur-impot-revenu"],
  "/calcul-indemnites-kilometriques": ["/calcul-heures-travail", "/salaire-brut-net", "/calcul-consommation-electrique", "/simulateur-impot-revenu"],
  "/simulateur-impot-revenu": ["/salaire-brut-net", "/simulateur-epargne", "/indemnite-licenciement", "/frais-de-notaire"],
  "/calcul-date-accouchement": ["/calcul-ovulation", "/calcul-age", "/calcul-imc", "/calcul-heures-travail"],
  "/simulateur-dca": ["/simulateur-epargne", "/calculateur-inflation", "/convertisseur-devises", "/simulateur-impot-revenu"],
  "/calculateur-inflation": ["/salaire-brut-net", "/simulateur-epargne", "/simulateur-dca", "/simulateur-impot-revenu"],
  "/simulateur-apl": ["/simulateur-impot-revenu", "/salaire-brut-net", "/simulateur-epargne", "/calcul-consommation-electrique"],
  "/calcul-calories": ["/calcul-imc", "/calcul-macros", "/calcul-age", "/calcul-date-accouchement"],
  "/calcul-macros": ["/calcul-calories", "/calcul-imc", "/calcul-metabolisme-base", "/conversion-poids"],
  "/calcul-masse-grasse": ["/calcul-imc", "/calcul-calories", "/calcul-age", "/calcul-date-accouchement"],
  "/simulateur-chomage": ["/salaire-brut-net", "/indemnite-licenciement", "/simulateur-impot-revenu", "/simulateur-micro-entreprise"],
  "/simulateur-micro-entreprise": ["/simulateur-impot-revenu", "/salaire-brut-net", "/calcul-tva", "/simulateur-chomage"],
  "/calcul-ovulation": ["/calcul-date-accouchement", "/calcul-imc", "/calcul-calories", "/calcul-age"],
  "/calcul-taux-endettement": ["/simulateur-pret-immobilier", "/frais-de-notaire", "/simulateur-impot-revenu", "/salaire-brut-net"],
  "/simulateur-mobilisation": ["/simulateur-bombe-nucleaire", "/simulateur-bunker", "/calcul-age", "/simulateur-chomage"],
  "/simulateur-bombe-nucleaire": ["/simulateur-mobilisation", "/simulateur-bunker", "/calcul-age", "/calcul-consommation-electrique"],
  "/simulateur-bunker": ["/simulateur-bombe-nucleaire", "/simulateur-mobilisation", "/calcul-surface-peinture", "/simulateur-epargne"],
  "/simulateur-pension-alimentaire": ["/simulateur-impot-revenu", "/salaire-brut-net", "/calcul-prime-activite", "/simulateur-chomage"],
  "/calcul-cout-garde-enfant": ["/simulateur-pension-alimentaire", "/calcul-prime-activite", "/simulateur-impot-revenu", "/calcul-date-accouchement"],
  "/simulateur-credit-conso": ["/simulateur-pret-immobilier", "/calcul-taux-endettement", "/simulateur-epargne", "/salaire-brut-net"],
  "/simulateur-bonus-ecologique": ["/simulateur-credit-conso", "/simulateur-impot-revenu", "/calcul-prime-activite", "/simulateur-epargne"],
  "/calcul-prime-activite": ["/simulateur-chomage", "/simulateur-apl", "/salaire-brut-net", "/simulateur-impot-revenu"],
  "/simulateur-retraite": ["/salaire-brut-net", "/simulateur-impot-revenu", "/simulateur-chomage", "/simulateur-epargne"],
  "/simulateur-salaire-alternant": ["/salaire-brut-net", "/simulateur-chomage", "/simulateur-micro-entreprise", "/calcul-prime-activite"],
  "/calculateur-budget-survie": ["/calculateur-autonomie", "/simulateur-apl", "/calcul-prime-activite", "/salaire-brut-net"],
  "/calculateur-autonomie": ["/calculateur-budget-survie", "/simulateur-epargne", "/simulateur-chomage", "/calcul-prime-activite"],
  "/simulateur-blackout": ["/calcul-consommation-electrique", "/prix-electricien", "/simulateur-bunker", "/calculateur-budget-survie"],
  "/calcul-capacite-emprunt": ["/simulateur-pret-immobilier", "/calcul-taux-endettement", "/frais-de-notaire", "/simulateur-epargne"],
  "/prix-macon": ["/prix-couvreur", "/prix-peintre", "/prix-electricien", "/prix-plombier"],
  "/prix-peintre": ["/calcul-surface-peinture", "/prix-macon", "/prix-couvreur", "/prix-electricien"],
  "/prix-electricien": ["/calcul-consommation-electrique", "/prix-macon", "/prix-plombier", "/prix-couvreur"],
  "/prix-plombier": ["/prix-electricien", "/prix-macon", "/prix-peintre", "/prix-couvreur"],
  "/prix-couvreur": ["/prix-macon", "/prix-chauffagiste", "/prix-electricien", "/prix-plombier"],
  "/prix-chauffagiste": ["/prix-plombier", "/prix-electricien", "/prix-couvreur", "/prix-macon"],
  "/conversion-temperature": ["/conversion-poids", "/conversion-longueur", "/convertisseur-devises", "/calcul-pourcentage"],
  "/conversion-poids": ["/conversion-longueur", "/conversion-temperature", "/calcul-imc", "/calcul-calories"],
  "/conversion-longueur": ["/conversion-poids", "/conversion-temperature", "/calcul-surface-peinture", "/calcul-imc"],
  "/calcul-moyenne": ["/produit-en-croix", "/calcul-pourcentage", "/calcul-age", "/simulateur-impot-revenu"],
  "/produit-en-croix": ["/calcul-moyenne", "/calcul-pourcentage", "/calcul-tva", "/conversion-temperature"],
  "/calcul-conges-payes": ["/salaire-brut-net", "/calcul-heures-travail", "/indemnite-licenciement", "/simulateur-chomage"],
  "/calcul-plus-value-immobiliere": ["/frais-de-notaire", "/simulateur-pret-immobilier", "/calcul-rentabilite-locative", "/calcul-revenus-fonciers"],
  "/calcul-rentabilite-locative": ["/calcul-revenus-fonciers", "/calcul-plus-value-immobiliere", "/frais-de-notaire", "/calcul-taux-endettement"],
  "/calcul-revenus-fonciers": ["/calcul-rentabilite-locative", "/calcul-plus-value-immobiliere", "/simulateur-impot-revenu", "/frais-de-notaire"],
  "/calcul-consommation-essence": ["/calcul-indemnites-kilometriques", "/calcul-consommation-electrique", "/conversion-temperature", "/calcul-pourcentage"],
  "/calcul-jours-ouvres": ["/calcul-conges-payes", "/calcul-heures-travail", "/salaire-brut-net", "/indemnite-licenciement"],
  "/calcul-interet-compose": ["/simulateur-epargne", "/simulateur-dca", "/calculateur-inflation", "/simulateur-impot-revenu"],
  "/calcul-malus-ecologique": ["/simulateur-bonus-ecologique", "/calcul-consommation-essence", "/simulateur-credit-conso", "/calcul-tva"],
  "/calcul-pgcd-ppcm": ["/calcul-moyenne", "/produit-en-croix", "/calcul-pourcentage", "/conversion-temperature"],
  "/calcul-duree-entre-dates": ["/calcul-jours-ouvres", "/calcul-age", "/calcul-conges-payes", "/calcul-heures-travail"],
  "/verificateur-devis": ["/calcul-tva", "/frais-de-notaire", "/simulateur-micro-entreprise", "/calcul-conges-payes"],
  "/calcul-ascendant-astrologique": ["/calcul-age", "/calcul-date-accouchement", "/calcul-ovulation", "/calcul-duree-entre-dates"],
  "/calcul-gratification-stage": ["/simulateur-salaire-alternant", "/salaire-brut-net", "/calcul-conges-payes", "/simulateur-chomage"],
  "/calcul-droits-succession": ["/frais-de-notaire", "/simulateur-impot-revenu", "/calcul-plus-value-immobiliere", "/simulateur-epargne"],
  "/simulateur-cout-voiture": ["/calcul-cout-kilometrique", "/calcul-consommation-essence", "/calcul-malus-ecologique", "/simulateur-bonus-ecologique"],
  "/calcul-cout-kilometrique": ["/simulateur-cout-voiture", "/calcul-indemnites-kilometriques", "/calcul-consommation-essence", "/simulateur-impot-revenu"],
  "/calcul-pension-reversion": ["/simulateur-retraite", "/simulateur-impot-revenu", "/calcul-droits-succession", "/salaire-brut-net"],
  "/calcul-surface-cercle": ["/calcul-volume-cylindre", "/calcul-surface-peinture", "/calcul-pourcentage", "/calcul-racine-carree"],
  "/calcul-volume-cylindre": ["/calcul-surface-cercle", "/calcul-surface-peinture", "/calcul-racine-carree", "/calcul-pourcentage"],
  "/calcul-racine-carree": ["/calcul-pgcd-ppcm", "/calcul-moyenne", "/produit-en-croix", "/calcul-surface-cercle"],
  "/calcul-poids-ideal": ["/calcul-imc", "/calcul-masse-grasse", "/calcul-metabolisme-base", "/calcul-calories"],
  "/calcul-metabolisme-base": ["/calcul-calories", "/calcul-macros", "/calcul-proteines", "/calcul-imc"],
  "/calcul-proteines": ["/calcul-macros", "/calcul-calories", "/calcul-metabolisme-base", "/calcul-masse-grasse"],
  "/calcul-besoin-sommeil": ["/calcul-metabolisme-base", "/calcul-calories", "/calcul-imc", "/calcul-age"],
  "/calcul-consommation-eau": ["/calcul-imc", "/calcul-metabolisme-base", "/calcul-calories", "/calcul-proteines"],
  "/calcul-risque-cardiovasculaire": ["/calcul-imc", "/calcul-metabolisme-base", "/calcul-poids-ideal", "/calcul-calories"],
  "/calcul-indice-glycemique": ["/calcul-calories", "/calcul-macros", "/calcul-imc", "/calcul-metabolisme-base"],
  "/calcul-age-metabolique": ["/calcul-metabolisme-base", "/calcul-imc", "/calcul-calories", "/calcul-masse-grasse"],
  "/calculateur-dpe": ["/calcul-consommation-electrique", "/simulateur-pret-immobilier", "/frais-de-notaire", "/calcul-rentabilite-locative"],
  "/simulateur-facture-gaz": ["/calcul-consommation-electrique", "/simulateur-pret-immobilier", "/prix-chauffagiste", "/calculateur-dpe"],
  "/simulateur-credit-auto": ["/simulateur-credit-conso", "/simulateur-cout-voiture", "/calcul-taux-endettement", "/calcul-capacite-emprunt"],
  "/calcul-score-stress": ["/calcul-risque-cardiovasculaire", "/calcul-besoin-sommeil", "/calcul-imc", "/calcul-age-metabolique"],
  "/simulateur-electrique-vs-thermique": ["/simulateur-cout-voiture", "/calcul-malus-ecologique", "/simulateur-bonus-ecologique", "/calcul-consommation-essence"],
  "/calcul-vignette-critair": ["/calcul-malus-ecologique", "/simulateur-bonus-ecologique", "/simulateur-cout-voiture", "/simulateur-electrique-vs-thermique"],
  "/calcul-remboursement-mutuelle": ["/calcul-risque-cardiovasculaire", "/calcul-score-stress", "/calcul-prime-activite", "/simulateur-impot-revenu"],
  "/calcul-allocation-familiale": ["/calcul-cout-garde-enfant", "/simulateur-pension-alimentaire", "/calcul-prime-activite", "/simulateur-apl"],
  "/calcul-taxe-fonciere": ["/frais-de-notaire", "/calcul-rentabilite-locative", "/calcul-revenus-fonciers", "/calcul-plus-value-immobiliere"],
  "/simulateur-assurance-emprunteur": ["/simulateur-pret-immobilier", "/calcul-capacite-emprunt", "/frais-de-notaire", "/calcul-taux-endettement"],
  "/simulateur-rendement-scpi": ["/calcul-rentabilite-locative", "/simulateur-epargne", "/simulateur-dca", "/calcul-revenus-fonciers"],
  "/simulateur-rente-viagere": ["/simulateur-retraite", "/simulateur-epargne", "/calcul-pension-reversion", "/calculateur-autonomie"],
  "/calcul-ifi": ["/calcul-taxe-fonciere", "/calcul-plus-value-immobiliere", "/calcul-droits-succession", "/calcul-rentabilite-locative"],
  "/simulateur-impot-societe": ["/simulateur-micro-entreprise", "/simulateur-impot-revenu", "/calcul-tva", "/calculateur-autonomie"],
  "/simulateur-amende-exces-vitesse": ["/calcul-malus-ecologique", "/calcul-vignette-critair", "/simulateur-cout-voiture", "/calcul-consommation-essence"],
  "/simulateur-loa-lld": ["/simulateur-credit-auto", "/simulateur-cout-voiture", "/simulateur-electrique-vs-thermique", "/calcul-malus-ecologique"],
  "/calcul-indice-inflammation": ["/calcul-calories", "/calcul-macros", "/calcul-imc", "/calcul-risque-cardiovasculaire"],
  "/calcul-prestation-compensatoire": ["/simulateur-pension-alimentaire", "/calcul-cout-garde-enfant", "/calcul-allocation-familiale", "/salaire-brut-net"],
  "/calcul-prise-poids-grossesse": ["/calcul-date-accouchement", "/calcul-imc", "/calcul-ovulation", "/calcul-calories"],
  "/calcul-amortissement-lmnp": ["/calcul-rentabilite-locative", "/calcul-revenus-fonciers", "/frais-de-notaire", "/calcul-plus-value-immobiliere"],
  "/simulateur-dividendes": ["/simulateur-impot-societe", "/simulateur-impot-revenu", "/simulateur-micro-entreprise", "/calcul-taux-endettement"],
};

interface RelatedCalculatorsProps {
  currentSlug: string;
}

export default function RelatedCalculators({ currentSlug }: RelatedCalculatorsProps) {
  const relatedSlugs = RELATED_MAP[currentSlug] || [];
  const related = relatedSlugs
    .map((slug) => ALL_CALCULATORS.find((c) => c.slug === slug))
    .filter(Boolean);

  if (related.length === 0) return null;

  return (
    <section className="mt-12">
      <h2 className="text-xl font-bold text-slate-800 mb-6">
        Calculateurs similaires
      </h2>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {related.map((calc) => (
          <a
            key={calc!.slug}
            href={calc!.slug}
            className="group bg-white rounded-xl border border-slate-200 p-4 hover:shadow-lg hover:shadow-slate-200/50 hover:-translate-y-0.5 transition-all duration-200"
          >
            <div className={`w-10 h-10 bg-gradient-to-br ${calc!.color} rounded-lg flex items-center justify-center text-lg shadow-sm`}>
              {calc!.emoji}
            </div>
            <p className="text-sm font-semibold text-slate-700 mt-3 group-hover:text-blue-600 transition-colors">
              {calc!.title}
            </p>
            <div className="mt-2 text-xs font-medium text-blue-600 flex items-center gap-1">
              Calculer
              <svg className="w-3 h-3 group-hover:translate-x-0.5 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
              </svg>
            </div>
          </a>
        ))}
      </div>
    </section>
  );
}
